export const ActionsType = {
  SET_PRODUCT: "SET_PRODUCT",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_PRODUCT_CART: "REMOVE_PRODUCT_CART",
  INC: "INC",
  DEC: "DEC",
};
